version: '3.4'

services:

  reviewdb:
    container_name: reviewdb
    environment:
      SA_PASSWORD: "Bostan46289145!"
      ACCEPT_EULA: "Y"
    restart: always
    ports:
      - "1433:1433"
  reviewgrpc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro