version: '3.4'

services:
  reviewgrpc:
    image: reviewgrpc:dev
    container_name: reviewGrpc
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "reviewGrpc"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_reviewgrpc$
    volumes:
      - C:\Users\pouyan\Documents\Visual Studio 2019\project\reservationmicroservice\src\Services\Review\reviewGrpc:/app
      - C:\Users\pouyan\Documents\Visual Studio 2019\project\reservationmicroservice\src\Services\Review:/src
      - C:\Users\pouyan\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_reviewgrpc$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_reviewgrpc$ \"/app/bin/Debug/net5.0/reviewGrpc.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true