// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using reviewGrpc.Data;

namespace reviewGrpc.Migrations
{
    [DbContext(typeof(reviewapi))]
    partial class reviewapiModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("reviewGrpc.Model.LoginReview", b =>
                {
                    b.Property<int>("LoginReviewID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("LoginID")
                        .HasColumnType("int");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<int?>("ReviewIDId")
                        .HasColumnType("int");

                    b.HasKey("LoginReviewID");

                    b.HasIndex("ReviewIDId");

                    b.ToTable("loginReviews");
                });

            modelBuilder.Entity("reviewGrpc.Model.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Explain")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rate")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("reviews");
                });

            modelBuilder.Entity("reviewGrpc.Model.LoginReview", b =>
                {
                    b.HasOne("reviewGrpc.Model.Review", "ReviewID")
                        .WithMany()
                        .HasForeignKey("ReviewIDId");

                    b.Navigation("ReviewID");
                });
#pragma warning restore 612, 618
        }
    }
}
